server:
  port: 9082
  
security:
  oauth2:
    client:
      client-id: orderService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.imooc.com:9090/oauth/token_key
        
spring:
  application:
    name: orderApi
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8082
        
sentinel:
  zookeeper:
    address: 127.0.0.1:2181
    path: /sentinel_rule_config
    
management:
  endpoints:
    promethus:
      enable: true
    web:
      exposure:
        include:
        - prometheus
        - info
        - health