global:
  scrape_interval:   15s
  
scrape_configs:
- job_name:       'springboot-app'

  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'

  static_configs:
  - targets: ['host.docker.internal:9082']
    labels:
      application: 'springboot-app'

- job_name: 'prometheus'

  scrape_interval: 5s

  static_configs:
  - targets: ['localhost:9090']

