version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.10
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
